export const subjects = {
  sem1: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },

  sem2: {
    it: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    cse: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    ece: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    eee: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    civil: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    mechanical: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    mining: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
  },

  /* sem3: {
    it: [
      "Environmental Science",
      "maths-3",
      "Analog Electronics",
      "DS using C",
      "Computer Architecture & Organization",
    ],
    cse: [
      "Environmental Science",
      "maths-3",
      "Analog Electronics",
      "DS using C",
      "Computer Architecture & Organization",
    ],
    ece: [
      "Managerial Economics and Accountancy",
      "maths-3",
      "Electronics Devices and Circuits",
      "Digital System Design",
      "Signals and Systems",
      "Network Analysis and Synthesis",
      "Constitution of Indian",
    ],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },
  sem4: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },
  sem5: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },
  sem6: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },
  sem7: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  }, */
};

